---
- name: Debug
  vars:
    msg: |-
      ansible_architecture: {{ ansible_architecture }}
      ansible_os_family: {{ ansible_os_family }}
      ansible_distribution: {{ ansible_distribution }}
      ansible_distribution_major_version: {{ ansible_distribution_major_version }}
      ansible_distribution_version: {{ ansible_distribution_version }}
      ansible_distribution_release: {{ ansible_distribution_release }}
      ansible_python_version: {{ ansible_python_version }}

      apache_install: {{ apache_install }}
      apache_version: {{ apache_version }}
      apache_packages:
        {{ apache_packages|to_nice_yaml(indent=2)|indent(2) }}
      apache_enable: {{ apache_enable }}
      apache_rcconf:
        {{ apache_rcconf|to_yaml(indent=2)|indent(2) }}
      apache_ssl: {{ apache_ssl }}
      apache_sslengine: {{ apache_sslengine }}
      apache_php: {{ apache_php }}
      apache_backup_conf: {{ apache_backup_conf }}
      apache_servername: {{ apache_servername }}
      apache_serveradmin: {{ apache_serveradmin }}
      apache_dir: {{ apache_dir }}
      apache_service: {{ apache_service }}
      apache_conf_path: {{ apache_conf_path }}
      apache_httpd_conf:
        {{ apache_httpd_conf|to_yaml(indent=2)|indent(2) }}
      apache_httpd_conf_modules:
        {{ apache_httpd_conf_modules|to_yaml(indent=2)|indent(2) }}
      apache_httpd_conf_ssl:
        {{ apache_httpd_conf_ssl|to_nice_yaml(indent=2)|indent(2) }}
      apache_httpd_conf_ssl_extra:
        {{ apache_httpd_conf_ssl_extra|to_yaml(indent=2)|indent(2) }}
      apache_httpd_conf_ssl_extra_absent:
        {{ apache_httpd_conf_ssl_extra_absent|to_yaml(indent=2)|indent(2) }}
      apache_vhost:
        {{ apache_vhost|to_nice_yaml(indent=2)|indent(2) }}
      apache_directory_blocks:
        {{ apache_directory_blocks|to_nice_yaml(indent=2)|indent(2) }}
      apache_alias:
        {{ apache_alias|to_nice_yaml(indent=2)|indent(2) }}
      apache_confd_dir_vhosts: {{ apache_confd_dir_vhosts }}
      apache_confd_dir_sections: {{ apache_confd_dir_sections }}
      apache_samples: {{ apache_samples }}
      apache_samples_list:
        {{ apache_samples_list|to_nice_yaml(indent=2)|indent(2) }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"

# EOF
