---
- name: "Httpd-vhosts: Create documnent roots for virtual hosts."
  ansible.builtin.file:
    state: directory
    path: "{{ item.DocumentRoot }}"
    owner: "{{ apache_data_owner }}"
    group: "{{ apache_data_group }}"
    mode: "{{ apache_dir_mode }}"
  loop: "{{ apache_vhost }}"
  loop_control:
    label: "{{ item.ServerName }}"
  when: item.create_document_root | d(false)

- name: "Httpd-vhosts: Configure virtual hosts in {{ apache_conf_path ~ '/extra/' }}"
  ansible.builtin.template:
    src: vhost.j2
    dest: "{{ apache_conf_path }}/extra/{{ item.ServerName }}.conf"
    owner: "{{ apache_data_owner }}"
    group: "{{ apache_data_group }}"
    mode: "{{ apache_data_mode }}"
    backup: "{{ apache_backup_conf }}"
  loop: "{{ apache_vhost }}"
  loop_control:
    label: "{{ item.ServerName }}"
  notify: Reload apache

- name: "Httpd-vhosts: Incl virtual hosts in {{ apache_conf_path ~ '/httpd.conf' }}"
  ansible.builtin.lineinfile:
    dest: "{{ apache_conf_path }}/httpd.conf"
    regexp: ^Include etc/apache{{ apache_version }}/extra/{{ item.ServerName }}.conf
    line: Include etc/apache{{ apache_version }}/extra/{{ item.ServerName }}.conf
    insertbefore: BOF
    backup: "{{ apache_backup_conf }}"
  loop: "{{ apache_vhost }}"
  loop_control:
    label: "{{ item.ServerName }}"
  notify: Reload apache

# EOF
