---
- name: "Httpd-modules: Load modules in {{ apache_conf_path }}/httpd.conf"
  ansible.builtin.lineinfile:
    dest: "{{ apache_conf_path }}/httpd.conf"
    regexp: ^\s*#*\s*LoadModule {{ item.module }}
    line: "    LoadModule {{ item.module }} libexec/{{ apache_dir }}/{{ item.mod }}"
    insertbefore: LoadModule
    backup: "{{ apache_backup_conf }}"
  loop: "{{ apache_httpd_conf_modules }}"
  notify: restart apache
  when: item.present|default(true)

- name: "Httpd-modules: Unload modules in {{ apache_conf_path }}/httpd.conf"
  ansible.builtin.lineinfile:
    dest: "{{ apache_conf_path }}/httpd.conf"
    regexp: ^\s*#*\s*LoadModule {{ item.module }}
    line: "    # LoadModule {{ item.module }}"
    insertbefore: LoadModule
    backup: "{{ apache_backup_conf }}"
  loop: "{{ apache_httpd_conf_modules }}"
  notify: restart apache
  when: not item.present|default(true)

- name: "Httpd-modules: Config PHP in {{ apache_conf_path }}/Includes/php.conf"
  ansible.builtin.blockinfile:
    dest: "{{ apache_conf_path }}/Includes/php.conf"
    block: |
      <IfModule dir_module>
        DirectoryIndex index.html index.php
      </IfModule>
      <FilesMatch "\.php$">
        SetHandler application/x-httpd-php
      </FilesMatch>
      <FilesMatch "\.phps$">
        SetHandler application/x-httpd-php-source
      </FilesMatch>
    owner: root
    group: www
    mode: "0640"
    create: true
    backup: "{{ apache_backup_conf }}"
  notify: restart apache
  when: apache_php|bool

# EOF
