---
- name: "Httpd-dirs: Configure directories in {{ apache_conf_path ~ '/Includes/' }}"
  ansible.builtin.template:
    src: directory-block.j2
    dest: "{{ apache_conf_path }}/Includes/{{ item.Includefile }}"
    owner: root
    group: www
    mode: "0644"
    backup: "{{ apache_backup_conf }}"
  loop: "{{ apache_directory_blocks }}"
  loop_control:
    label: "{{ item.Directory }}"
  notify: Reload apache

# EOF
