---

- name: "packages: Install packages"
  community.general.pkgng:
    name: "{{ apache_packages }}"
  register: result
  until: result is succeeded
  retries: "{{ freebsd_install_retries }}"
  delay: "{{ freebsd_install_delay }}"
  when: freebsd_install_method == 'packages'

- name: "packages: Debug install packages"
  ansible.builtin.debug:
    var: result
  when: apache_debug|bool

- name: "packages: Install ports"
  community.general.portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages|default(true) }}"
  loop: "{{ apache_packages }}"
  register: result
  until: result is succeeded
  retries: "{{ freebsd_install_retries }}"
  delay: "{{ freebsd_install_delay }}"
  when: freebsd_install_method == 'ports'

- name: "packages: Debug install ports"
  ansible.builtin.debug:
    var: result
  when: apache_debug|bool
# EOF
...
