---
- name: "Rc_conf: configure /etc/rc.conf"
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    regexp: ^\s*{{ item.key }}\s*=(.*)$
    line: '{{ item.key }}="{{ item.value }}"'
    backup: "{{ apache_backup_conf }}"
  loop: "{{ apache_rcconf }}"
  notify: graceful apache

- name: "Rc_conf: Enable and Start Apache"
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    regexp: ^\s*{{ apache_service }}_enable\s*=(.*)$
    line: '{{ apache_service }}_enable="YES"'
    backup: "{{ apache_backup_conf }}"
  notify: enable and start apache
  when: apache_enable | bool

- name: "Rc_conf: Disable and Stop Apache"
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    regexp: ^\s*{{ apache_service }}_enable\s*=(.*)$
    line: '{{ apache_service }}_enable="NO"'
    backup: "{{ apache_backup_conf }}"
  notify: disable and stop apache
  when: not apache_enable | bool

# EOF
